version: '3.8'
services:
  # avax_transaction_api:
  #   build:
  #     context: ./avax-transaction-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5628:5628"
  #   restart: always
  crawl_crypto_news_service:
    build:
      context: ./crawl-crypto-news-service
      dockerfile: Dockerfile
    ports:
      - "8889:8000"
  # nextjs_ethereum_wallet:
  #   build:
  #     context: ./crawl-crypto-news-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3025:3000"        