version: '3.8'
services:
  avax_transaction_api:
    build:
      context: ./avax-transaction-api
      dockerfile: Dockerfile
    ports:
      - "5628:5628"
    restart: always
  crawl_crypto_news_service:
    build:
      context: ./crawl-crypto-news-service
      dockerfile: Dockerfile
    ports:
      - "8889:8000"
  nextjs_ethereum_wallet:
    build:
      context: ./nextjs-ethereum-wallet
      dockerfile: Dockerfile
    ports:
      - "3025:3000"
  hackathon_api:
    build:
      context: ./hackathon_avax_be
      dockerfile: dockerfile
    ports:
      - "8181:8181"
    depends_on:
      db:
        condition: service_started
  
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=example  
      - MYSQL_ALLOW_EMPTY_PASSWORD=true 
      - MYSQL_DATABASE=avalanche_hackathon_db   
    ports:
      - 3377:3306
    volumes:
      - mysql-data:/var/lib/mysql    # Persist MySQL data
      - ./hackathon_avax_be/database:/docker-entrypoint-initdb.d


volumes:
    mysql-data: