FROM node:18-alpine

WORKDIR /app

# Set Node.js memory limit to 2GB
ENV NODE_OPTIONS="--max-old-space-size=2048"

COPY package*.json ./

RUN yarn global add @nestjs/cli
# RUN apt update && apt-get install -y graphicsmagick imagemagick

RUN yarn install --prod 

COPY . .

RUN yarn build

EXPOSE 8001

CMD ["yarn", "start:prod"]
