COIN_DESK_URL = "https://www.coindesk.com/"
NEW_BIT_URL = "https://news.bitcoin.com/"
THE_CRYPTO_BASIC_URL="https://thecryptobasic.com/"
COIN_TELEGRAPH_URL="https://cointelegraph.com/"
U_TODAY_URL="https://u.today/"
DECRYPT_URL="https://decrypt.co/"
BEIN_CRYPTO_URL="https://beincrypto.com/"
CRYPTO_NEWS_URL="https://cryptonews.com/"
CRYPTO_POTATO_URL="https://cryptopotato.com/"
THE_BLOCK_URL="https://www.theblock.co/"
CRYPTO_NEWS_URL = "https://cryptonews.com/"

BEIN_CRYPTO_NEWS_URL = "https://beincrypto.com/"

BLOCK_WORKS_URL="https://blockworks.co/"
BLOCK_WORKS_MARKET_URL="https://blockworks.co/category/markets"
BLOCK_WORKS_ANALYSIS_URL="https://blockworks.co/category/analysis"