version: '3.8'

services:
  # FastAPI application service
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your Dockerfile
    ports:
      - "8889:8000"  # Exposes port 8000 in the container to 8889 on the host
    # labels:
    #   - 'traefik.enable=true'
    #   # Use an IP-based access rule (you can use the IP and port directly in Traefik)
    #   - 'traefik.http.routers.app.rule=Host(`43.207.2.31`)'  # Use IP address instead of domain
    #   - 'traefik.http.routers.app.entrypoints=https'  # Use HTTPS entrypoint
    #   - 'traefik.http.services.app.loadbalancer.server.port=8000'  # Point to the correct internal port of your app (8000)
    #   - 'traefik.http.routers.app.tls=true'  # Enable TLS (HTTPS)
    #   - 'traefik.http.routers.app.tls.certresolver=letsencrypt'  # Use Let's Encrypt for SSL

# networks:
#   traefik-net:
#     external: true
