version: '3.8'

services:
  # FastAPI application service
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your Dockerfile
    ports:
      - "8889:8000"  # Exposes port 8000 in the container to 8889 on the host
